export default {
  cartNumber: null,
  oneCity: null,
  formNoChange: null,
  loading: false,
  edit: false,
  headerInfo: {},
  cityCategoryId: 0,
  pointType: 0,
  giveWayCondition: null,
  indoorClientId: null,
  indoorClientId: 0,
  orderId: "",
  orderType: "",
  agentInfo: {},
  customerInfo: {},
  financial: {},
  transferId: "",
  financeInfo: {},
  menuData: [],
  publicPath: "",
  isVip: "",
  overdueInfo: {},
  saleReportId: "",
  newsList: [],
  systemData: [],
  haveUnreadMessage: null
};
